### ISSUE TITLE
Missed some icons

### ISSUE THREAD

**Issue by abdonrd** [file-icons/vscode#1]
Atom vs VSCode:

<img width="184" alt="screen shot 2017-01-03 at 11 22 00" src="https://cloud.githubusercontent.com/assets/1007051/21605102/31349652-d1a7-11e6-9879-b73f1af2547c.png"> <img width="192" alt="screen shot 2017-01-03 at 11 22 08" src="https://cloud.githubusercontent.com/assets/1007051/21605104/3533d786-d1a7-11e6-8de1-396b6e02f0db.png">

And the icons are not centered with the same size.

**Comment by DanBrooker** [comment]
0.0.2 has fixed a number of the missing icons

**Comment by abdonrd** [comment]
Yay! Thanks @DanBrooker!

**Comment by abdonrd** [comment]
Missed: `.gitignore`, `bower_components`, `node_modules`.

<img width="479" alt="screen shot 2017-01-04 at 11 54 59" src="https://cloud.githubusercontent.com/assets/1007051/21640239/d7e776c2-d274-11e6-9e8f-52d64c2b7a21.png">

**Comment by DanBrooker** [comment]
@abdonrd ok I think 0.0.3 should take care of those and a few others

**Comment by abdonrd** [comment]
Thanks @DanBrooker!

<img width="433" alt="screen shot 2017-01-05 at 10 55 23" src="https://cloud.githubusercontent.com/assets/1007051/21676502/1da19ac8-d336-11e6-9d92-35a1b1e08729.png">
