### ISSUE TITLE
dockerfile icon not showing.

### ISSUE THREAD

**Issue by Tallmaris** [file-icons/vscode#13]
Hi there,

I've recently installed vscode and added your file-icons but I noticed that the dockerfile is not showing its icon. The .dockerignore works ok. I've tried both upper and lowercase D in case it was the problem...
![image](https://cloud.githubusercontent.com/assets/473840/24710984/984e5cda-1a16-11e7-8374-1c4d5c069b7f.png)

Other than that, amazing library!

**Comment by DanBrooker** [comment]
It should be working (but isn't). As far as I can tell, its listed in the config correct. `.Dockerfile` works for some reason

**Comment by Tallmaris** [comment]
I think it's because of just checking the extension and that file has no extension? :/

**Comment by DanBrooker** [comment]
Should be treating it as a fileName as per this documentation.

> fileNames associates file names to icons. The key in the set is the full file name, not including any path segments. Patterns or wildcards are not supported. File name matching is case insensitive. A 'fileName' match is the strongest match, and the icon associated to the file name will be preferred over an icon of a matching fileExtension and also of a matching language Id.

https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_adding-a-new-icon-theme
