### ISSUE TITLE
.gitignore has no color.

### ISSUE THREAD

**Issue by gluons** [file-icons/vscode#3]
`.gitignore` file has no color.

<img width="145" alt="default" src="https://cloud.githubusercontent.com/assets/4688092/21756402/90a9bc10-d653-11e6-9618-9ce4a1a39bbd.PNG">

**Comment by abdonrd** [comment]
It is a VSCode issue: https://github.com/Microsoft/vscode/issues/178 😕

**Comment by DanBrooker** [comment]
Colour has been added in 0.0.4
