### ISSUE TITLE
Color only for modified files

### ISSUE THREAD

**Issue by Mushr0000m** [file-icons/vscode#34]
Hi and great work !
Do you think it would be possible to have an option like in Atom to color only an icon if it's changed (in GIT) ?
Thanks

**Comment by DanBrooker** [comment]
Hi @Mushr0000m, 

I'm not sure, VSCode's themes work a little differently to Atom. It might be possible with a more in-depth extension, but it's not something I can quickly add.

Thanks,
Dan

**Comment by tiagoboeing** [comment]
Yes, for this i use extensions Git:
- https://github.com/eamodio/vscode-gitlens

**Comment by DanBrooker** [comment]
Thanks @tiagoboeing I'll close this issues in favour of that plugin.
