### ISSUE TITLE
.test.js files have .js icons

### ISSUE THREAD

**Issue by seanfmcd** [file-icons/vscode#35]
Hi. This issue was brought up and fixed in the atom version https://github.com/file-icons/atom/issues/732. Is it possible to do the same in vscode?

I love this theme btw.

**Comment by markov00** [comment]
The same for the ts test files updated here: https://github.com/file-icons/atom/blob/4fbfdda/config.cson#L4002
Isn't it just a matter of updating the submodule?

**Comment by DanBrooker** [comment]
The file extension matching works differently in vscode compared to atom. I've updated the icon list with upstream changes but I think it'll still show as a .js file

**Comment by DanBrooker** [comment]
@lensbart there's a couple of things that could be done to improve the matching

1. more restrictive regex in the atom icon listings, i.e regex that generate > 1000 matches
2. some way of adding a regex match to vscode as plugin code or a PR to vscode
3. a json file of additions or overrides, it's simple and people could easily add to it, but it has a higher maintenance cost

**Comment by Alhadis** [comment]
Fixed in b6439ae (if not earlier…)
