### ISSUE TITLE
More grey possible?

### ISSUE THREAD

**Issue by therealmarv** [file-icons/vscode#4]
Hi,

is it possible to to make file icons text and folders more greyish? I have the feeling they pop a little bit too much out.

Screenshot for comparison. I like the Atom look more.
![image](https://cloud.githubusercontent.com/assets/1050582/22566014/50c51f1a-e9c5-11e6-9093-cf48e185fe6d.png)

By the way... I published recently my Atom theme (most in the marketplace are not good). I will recommend file-icons in the next version! :)
https://github.com/therealmarv/vscode-theme-dark-atom-dark-green-cursor

**Comment by therealmarv** [comment]
just a additional: I mean only the text color and folder color (not the background!)

**Comment by DanBrooker** [comment]
The text colour is from your colour theme not from the icons

**Comment by therealmarv** [comment]
Oh okay. Do you mayvr know which tmtheme key is used for that text color? I will play around and will try to change that color.

**Comment by DanBrooker** [comment]
No sorry, maybe check the example themes https://github.com/Microsoft/vscode-extension-samples/tree/master/theme-sample
