### ISSUE TITLE
Icon request: .pre-commit-config.yml

### ISSUE THREAD

**Issue by Benjamin-Lee** [file-icons/vscode#42]
[Pre-commit](https://pre-commit.com) is a pretty popular framework for managing pre-commit hooks. Would it be possible to get an icon for the config file (.pre-commit-config.yml)?

**Comment by Alhadis** [comment]
I had to add this manually because [`genex`](https://github.com/alixaxel/genex.js) was unable to parse a filename-matching regex:

~~~
/^\.pre-commit\b.*\.ya?ml$/i skipped regex has too many cases to generate: Infinity
~~~
