### ISSUE TITLE
File associations ?

### ISSUE THREAD

**Issue by SnO2WMaN** [file-icons/vscode#46]
VSCode Material Icons has a configuration called [File Associations](https://github.com/PKief/vscode-material-icon-theme#file-associations), but aren't you going to implement it in File Icons?

Now I have a lot of yml configuration files and poor visibility, so I want to customize the icons for some files ...

**Comment by Alhadis** [comment]
> but aren't you going to implement it in File Icons?

Not yet. The features you speak of are already possible in Atom, but this package only implements a specific subset of its functionality. I plan on rewriting the package to be generic, environment-agnostic JavaScript so only a minimal amount of editor-specific tampering is needed.

I'm not familiar enough with the expectations of VSCode users, though, and I'm puzzled by its notion of "icon themes" and using JSON to describe something that's easier to express with a stylesheet... 😕

**Comment by SnO2WMaN** [comment]
I appreciate your answer to my question, closing this issue.
