### ISSUE TITLE
Update some icons

### ISSUE THREAD

**Issue by abdonrd** [file-icons/vscode#5]
I attach images VSCode vs Atom:

<img width="268" alt="screen shot 2017-02-10 at 19 47 19" src="https://cloud.githubusercontent.com/assets/1007051/22839508/00fc4ae8-efca-11e6-9ffc-ea7039b2f083.png">
<img width="268" alt="screen shot 2017-02-10 at 19 47 54" src="https://cloud.githubusercontent.com/assets/1007051/22839506/00f92d40-efca-11e6-8a75-9ee0a57a2895.png">
<img width="266" alt="screen shot 2017-02-10 at 19 48 17" src="https://cloud.githubusercontent.com/assets/1007051/22839507/00fbc924-efca-11e6-970d-8de09f1de98a.png">

**Comment by DanBrooker** [comment]
Latest version has the new atom icons.
README.md is just getting the markdown icon because of the rule precedence in vscode not sure I can do much about that.

**Comment by abdonrd** [comment]
Thanks! :)

**Comment by abdonrd** [comment]
Oops! The `polymer.json` and the `Static` files are with other icons:

<img width="303" alt="screen shot 2017-02-11 at 02 12 43" src="https://cloud.githubusercontent.com/assets/1007051/22849718/0a572c12-f000-11e6-87d5-5801f4fae659.png">

**Comment by abdonrd** [comment]
Friendly ping to @DanBrooker. :)

**Comment by DanBrooker** [comment]
Hey, I haven't had time to fix this yet, but it's the same issue as with the other icons, where vscode seems to prioritise file extension over file name. I'll open a new issue explaining this and close the issues that have the same issue.

PRs welcome if you wanted to try fix it :)

**Comment by DanBrooker** [comment]
See #10

**Comment by abdonrd** [comment]
Got it, thanks Daniel!
