### ISSUE TITLE
Untitled files don't show the icon of their language mode (and instead shows an icon of a blank file)

### ISSUE THREAD

**Issue by KLaurence** [file-icons/vscode#55]
Some themes like Seti show icons for opened files based on what the current language modes of those files are.

**Comment by Livven** [comment]
This also applies to the language mode selector. I believe this is due to microsoft/vscode#106872 and fixed by setting the [`languageIds` field](https://code.visualstudio.com/api/extension-guides/file-icon-theme#file-association) in this theme.

**Comment by Alhadis** [comment]
Fixed by 479092d and a8c812d. You'll see it in the next release (once I finally finish it):

<img src="https://user-images.githubusercontent.com/2346707/163563737-aa19acdf-f964-408b-8d0c-b69393c849ec.png" alt="Figure 1" width="631" />
