### ISSUE TITLE
rollup.config.js not recognized

### ISSUE THREAD

**Issue by bennypowers** [file-icons/vscode#57]
<img width="257" alt="Screen Shot 2020-09-26 at 21 33 41" src="https://user-images.githubusercontent.com/1466420/94347796-f77c7300-003f-11eb-83ce-4548a2e6a5ad.png">

Thanks for your work maintaining this package

**Comment by Alhadis** [comment]
Damn, WTF is [this](https://github.com/file-icons/vscode/blob/736e2709443c2651d98f9ddd107b4457e49127bc/icons/file-icons-icon-theme.json#L35774)? 😂

~~~diff
 			"riemann.config": "_clojure_auto-maroon_l",
 			"robots.txt": "_robots_dark-cyan_l",
-			"rollup.config.": "_rollup_medium-red_l",
 			"rsyncd.conf": "_rsync_dark-purple_l",
 			"irbrc": "_ruby_medium-red_l",
~~~

Yeah, I think an existent file extension might help. 👍 Hold on.
