### ISSUE TITLE
azure-pipelines.yml not recognized

### ISSUE THREAD

**Issue by bennypowers** [file-icons/vscode#59]
See also #57

**Comment by Alhadis** [comment]
Christ. This one's harder to figure out. 😰 Just to clarify, you *are* seeing the usual YAML icon, yeah? What about directories named `.azure-pipelines`…?

**Comment by bennypowers** [comment]
I created an empty dir `/.azure-pipelines` and it had a normal folder icon****

**Comment by Alhadis** [comment]
Oh man, I don't have the strength to deal with this tonight. I'm legitimately an inch away from submitting a report upstream asking Microsoft if they're allergic to CSS.

Seriously, [what the hell is this](https://code.visualstudio.com/api/extension-guides/file-icon-theme#icon-definitions)? They build an editor with web technologies, but say "nah screw it" and decide to rip out two thirds of what makes web tech so awesome?

It's late, I'm aimlessly bitching into thin air, but holy hell, if this were a simple stylesheet, I'm 100% sure this package wouldn't be so fucking flaky.

I'll have to punt this to the next version, mate. 😞 Sorry.

**Comment by bennypowers** [comment]
lol you're preaching to the choir man, I miss atom something fierce. undeniably the better platform IMHO. atom-community is doing the Lord's work, but there are few contributors, not much in the way of resources and a lot yet to do.

**Comment by Alhadis** [comment]
**_Finally_** fixed in b6439ae. Took an entire rewrite of the import machinery.

**Comment by bennypowers** [comment]
_quake3impressive.wav_
