### ISSUE TITLE
Question: What is the project's license?

### ISSUE THREAD

**Issue by mnaglic** [file-icons/vscode#66]
Hello, I'm considering using file-icons in my own open source project but I can't seem to find the LICENSE file? Is file-icons released under any license? If so, could you please add the LICENSE file?

**Comment by haykam821** [comment]
The `package.json` seems to indicate that it is licensed under the MIT License:

https://github.com/file-icons/vscode/blob/d9221c77533345a136302cb04b2a3655a5278a9e/package.json#L65

**Comment by mnaglic** [comment]
> The `package.json` seems to indicate that it is licensed under the MIT License:
> 
> https://github.com/file-icons/vscode/blob/d9221c77533345a136302cb04b2a3655a5278a9e/package.json#L65

I'm not sure that's enough. [MIT license text](https://opensource.org/licenses/MIT) specifically includes this sentence:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

**Comment by Alhadis** [comment]
@mnaglic The canonical repository is [`file-icons/icons`](https://github.com/file-icons/icons), and the license is [ISC](https://github.com/file-icons/icons/blob/4eac7ad656030b7704e139e222d4666a9151f93f/LICENSE.md) (the same as MIT, but shorter). This repository (`file-icons/vscode`) is VSCode-specific and has very little material that's worthy of reuse.
