### ISSUE TITLE
webpack.*.js rendering with JS icons

### ISSUE THREAD

**Issue by angelica-bocanegra** [file-icons/vscode#67]
webpack.*.js rendering with Javascript Icons. 
Although `webpack.dev.js` and `webpack.prod.js` already exists in `scripts/import-fixes.json` the icons are rendering with Javascript icons. 
![webpack-vscode-atom (1)](https://user-images.githubusercontent.com/58057927/99896737-7fe95e00-2ce7-11eb-8684-c593697acc3c.png)

Note: The icon only renders when its extension matches the `import-fixes.json`.
eg. 
`webpack.dev.js` does not match 
`anything.webpack.dev.js` matches
![ezgif com-gif-maker (12)](https://user-images.githubusercontent.com/58057927/99896942-4d406500-2ce9-11eb-84aa-4edeaf355629.gif)

**Comment by Brianzchen** [comment]
@Alhadis I'd really like to see this as someone who likes to break up my webpack configs. Any thoughts on it?
