### ISSUE TITLE
License

### ISSUE THREAD

**Issue by superherointj** [file-icons/vscode#69]
Where is the license for this project?

**Comment by Alhadis** [comment]
[Here](https://github.com/file-icons/icons/blob/master/LICENSE.md).

This repository only contains the icon-theme mappings, and the script to regenerate them, which are both of which are specific to VSCode and unlikely to be of much use anywhere else. Nonetheless, you can find their license declared in [`package.json`](https://github.com/file-icons/vscode/blob/1f290c52dad59e65114ad2b1e9798092a02991d8/package.json#L65).

**Comment by superherointj** [comment]
`package.json` says "license": "MIT". 
`https://github.com/file-icons/icons/blob/master/LICENSE.md` says "ISC".
I am packaging the vscode extension for NixOS, should I use MIT or ISC?
Btw thanks for answering promptly. :-)

**Comment by Alhadis** [comment]
> I am packaging the vscode extension for NixOS

Are you packaging the VSCode extension specifically? If so, use `MIT`. Otherwise, use `ISC`.

In any case, both licenses are effectively equivalent. The only difference is that ISC is shorter because it omits redundant legal clauses stipulated by the [Berne Convention](https://en.wikipedia.org/wiki/Berne_Convention).

**Comment by superherointj** [comment]
I am packaging VSCode extension specifically, I'll use MIT, thanks for clarifying. Thanks again!

**Comment by Alhadis** [comment]
No problem!

I've added a `LICENSE.md` file that contains the proper attribution (I took over maintenance duties of this fork in mid-2019, hence the differing license).
