### ISSUE TITLE
Travis and webpack file don't get correct icon.

### ISSUE THREAD

**Issue by gluons** [file-icons/vscode#7]
**VSCode:**
![vscode](https://cloud.githubusercontent.com/assets/4688092/22864183/4c6a609e-f17f-11e6-9336-92d1377d7bdf.PNG)

**Atom:**
![atom](https://cloud.githubusercontent.com/assets/4688092/22864188/56ade8a0-f17f-11e6-92f9-a673ffebaadb.PNG)

**Comment by DanBrooker** [comment]
I'm grouping a couple of these issues in #10 as they have the same cause
