### ISSUE TITLE
Language Select Mode does not show icons

### ISSUE THREAD

**Issue by cvharris** [file-icons/vscode#76]
When opening the language select mode, file icons ought to appear next to the different language types:

Right now they're all blank:
![Screen Shot 2021-08-23 at 10 05 54](https://user-images.githubusercontent.com/4013888/130471017-fa0f5463-3e74-4826-945b-72c24ac4ece6.png)

Here's what the supported icons look like in VSCode's own Seti file icon theme:
![Screen Shot 2021-08-23 at 10 06 07](https://user-images.githubusercontent.com/4013888/130471092-b5db8d83-de5d-41b6-8348-418e6123414f.png)

**Comment by Alhadis** [comment]
Yikes, that's bad. Looking at it now…

**Comment by Daniel-r54** [comment]
> Yikes, that's bad. Looking at it now…

Hello Creator of this extension, i noticed that too, that the icons doesnt show off at all.
If i delete it again or change the file icon with e.g. Seti and back to yours again (thought it could be an bug or something) it still doesnt work properly.
restarting Vscode with your activated extension dont works too.

**Comment by Alhadis** [comment]
@Daniel-r54 Be patient, please. I'm still working on it—disabling the extension won't do anything, because it never had support for language-icons to begin with.

**Comment by Daniel-r54** [comment]
> Be patient, please. I'm still working on it—disabling the extension won't do anything, because it never had support for language-icons to begin with.

Ok sorry if i attacked you, i just found this.
