### ISSUE TITLE
Fix Stylelint icon

### ISSUE THREAD

**Issue by abdonrd** [file-icons/vscode#8]
If the .stylelintrc file has extension, doesn't show the correct icon:

<img width="235" alt="screen shot 2017-02-15 at 12 26 23" src="https://cloud.githubusercontent.com/assets/1007051/22972474/0c837c34-f37a-11e6-8644-7dede8b3db06.png">

**Comment by DanBrooker** [comment]
I'm grouping a couple of these issues in #10 as they have the same cause
