### ISSUE TITLE
Icons appearing washed out

### ISSUE THREAD

**Issue by cvharris** [file-icons/vscode#9]
Some of the Icons, specifically anything with 'yellow' are appearing a little washed out in VSCode as opposed to Atom.

![screen shot 2017-02-28 at 9 49 07 am](https://cloud.githubusercontent.com/assets/4013888/23412474/4165b1ee-fd9b-11e6-8a62-86f459cba7c5.png)

I'd expect the colors to carry over better. Some icons with yellow such as Gruntfile and .babelrc are looking pretty spot-on, so perhaps it's jsut the javascript icons.

**Comment by DanBrooker** [comment]
The atom version does some fancy runtime checking on your theme and can pick a different yellow based on that. I think I can change the default yellow in this package to the one you see in atom, as it does look nicer.

**Comment by ajmichaels** [comment]
I actually like the washed out colors, as it's less distracting than the atom version's colors but still clear enough to easily let me scan through the sidebar.  Would it be possible to leave the washed out version as a config setting?

**Comment by cvharris** [comment]
I wonder if it's possible to incorporate that runtime code for changing the shades depending on your active theme settings, like you mentioned it was doing in Atom.

**Comment by ryanwmarsh** [comment]
Love these icons @DanBrooker. Watching this thread to be notified when the color gets fixed.

**Comment by DanBrooker** [comment]
@cvharris At the moment the icon and theme plugin interface is very static so dynamically changing colours isn't supported. I imagine an full on extension might be able to do it, but no plans for that at the moment.

**Comment by cvharris** [comment]
Icons look great, nice @DanBrooker
